etiennebacher/altdoc

- DESCRIPTION
- NEWS.md
- R/build.R
- R/reference.R
- R/update.R
- R/use.R
- R/utils.R
- man/init.Rd
- man/update_docs.Rd
For projects where the reference section is very "non-standard", it allows us to use a custom script to build the reference section (used in `r-polars`)
> Argument `custom_reference`

- DESCRIPTION
- NEWS.md
- R/build.R
- R/preview.R
- R/use.R
- man/init.Rd
The function signature calls `getOption()`, so users can either suppress the preview manually every time, or set a global option.
This is useful when testing interactively in my environment (vscode + wsl)
> use_*() get a preview argument

- DESCRIPTION
- NEWS.md
`altdoc` 0.2.2 was released using the last commit before @rempsyc's first commit (cf #58) so I bump NEWS and description
> Bump news and description following 0.2.2

- R/import.R
- R/utils-rmd.R
When there is a `README.qmd` or a `README.Rmd` in the root directory, that file is rendered automatically to `README.md` at the very start of the process.
Then, `README.md` is copied over as we were doing before.
Since we now render all files with Quarto, the assets are stored in `README.markdown_strict_files/` rather than `README_assets/`. I have kept both just in case we roll back to `rmarkdown::render` at some point.
> render README.qmd/Rmd automatically

- .github/workflows/altdoc.yaml
- inst/misc/altdoc.yaml
I can't figure out how to make the "Deploy to GitHub pages" step work with the `r2u` container. I think this is due to the fact it is a container so we need to install and reconfigure git inside the container, but I've tried several things and nothing worked.
So here I'm just adapting the `pkgdown` workflow for our needs. It's no big deal to have a setup 30sec slower, most of the time will be spent on rendering the website for packages with more vignettes/man pages
> Change GHA to `pkgdown`-like GHA

- R/rd2qmd.R
Directory name is "r-polars", but we want to load "polars"
> Use package name, not root directory name

- R/preview_docs.R
- R/settings_mkdocs.R
- R/settings_quarto_website.R
Not sure when the `preview` part came back, I had removed it in a previous PR.
Always write the yaml with indentation, otherwise it breaks mkdocs
> Misc fixes for mkdocs

- R/import_misc.R
Close #185
Problem was that there are both `@vincent` and `@vincentarelbundock` in the NEWS file. Replacing the latter works fine, but then the replacement of the former messes up the first replacement.
> Fix `.parse_news()` when two names have the same root

- DESCRIPTION
- R/import_readme.R
- inst/preamble/preamble_vignettes_qmd.yml
`.import_readme()` now uses the quarto preamble for vignettes
the preamble now includes a line to prevent adding the exension automatically.
not sure about the behavior in .Rmd.
> img preamble in quarto

- R/settings_mkdocs.R
- tests/testthat/test-update_docs.R
- tests/testthat/test-use_mkdocs.R
This does two things:
* do not remove the `.md` extension anymore in `mkdocs.yaml`, otherwise the files do not appear on the website (tested with `polars`)
* simplify the cleanup at the end: basically we can remove `docs` altogether and rename `site` to `docs`
@vincentarelbundock could you test with `marginaleffects` to see if this breaks anything?
> Fix mkdocs

- R/settings_mkdocs.R
- R/utils.R
In the polars workflow, we set up a `.venv` folder where `mkdocs` is installed. The aim of this PR is to prioritize the `.venv` folder over the more general python installation
> Find the best python installation

- .github/workflows/R-CMD-check.yaml
- .github/workflows/test-coverage.yaml
- R/check.R
- R/preview_docs.R
- R/setup_docs.R
- tests/testthat/examples/examples-qmd/with-preamble.qmd
- tests/testthat/examples/examples-qmd/without-preamble.qmd
- tests/testthat/helper.R
- tests/testthat/test-freeze.R
- tests/testthat/test-preview_docs.R
- tests/testthat/test-qmd2md.R
- tests/testthat/test-rd2qmd.R
- tests/testthat/test-settings.R
- tests/testthat/test-setup_docs.R
- tests/testthat/test-setup_github_actions.R
- tests/testthat/test-utils.R
Mostly basic coverage for `.read_freeze()`, `.rd2qmd()` and `.qmd2md()`. 
The rendering functions are quite dense. Now that their behavior is a bit more stable we should refactor them to extract common helper functions that are easier to test.
Also minor changes:
* `setup_docs()` now directly errors if `altdoc` already exists and `overwrite = FALSE`
* better errors in `preview_docs()`
> Improve test coverage

- R/import_man.R
- R/import_vignettes.R
- R/utils.R
- tests/testthat/test-import_man.R
Keep getting an error about "can't read RDS" in the polars CI. Maybe it's just better to not write this file because it won't be updated in `main` and therefore not available to us
> Do not try to write freeze.rds in CI workflows

- R/rd2qmd.R
Close #217 
There are several `<div>` in man pages of R6 methods, we only want to remove the last one (and the `</document>` coming after)
> Fix man pages of R6 methods

- R/freeze.R
- R/import_man.R
- R/import_vignettes.R
Close #219 
I think the error when we have `freeze` + `parallel` is that we write to `freeze.rds` for each file individually, right after they're rendered. This is an issue when several processes want to write to the same file at the same time.
This PR *should* fix this by updating all hashes at once after all man pages (or vignettes) have been rendered.
@vincentarelbundock can you try with this branch to see if it solves #219?
> Update hashes all at once

- R/import_readme.R
- R/render_docs.R
- tests/testthat/test-import_man.R
- tests/testthat/test-render_docs.R
* `freeze = TRUE` now also skips the README
* refactor `.import_readme()`
* add test for basic workflow with `quarto_website`
> Allow `freeze` for README

- R/preview_docs.R
`urlBrowser()` is a useless call with docsify and docute, because we need a live server to display the website, so that just launches an empty browser.
But it turns out that `servr::httw` works perfectly fine, even in weird setups like mine: WSL Ubuntu on Windows.
This removes the `rstudioapi` check and calls this immediately.
> preview_docs works on non-RStudio systems

- R/settings_mkdocs.R
I don't really know why, but sometimes there is a gitignore file in the "docs/vignettes" folder only that ignores `.R` and `.html` files. This is a problem because it means that the files created by mkdocs are not pushed at the end of the `altdoc` workflow, and therefore they direct to 404 on the deployed website.
This PR is a patch for that (I'm not sure why this gitignore appears)
> mkdocs: remove the gitignore in "docs/vignettes" if there is one

- R/setup_docs.R
- README.md
- README.qmd
- vignettes/get-started.Rmd
I was a bit confused by the error message about virtual environment for `mkdocs`, because it seemed like I did not in fact need to activate the environment, because `altdoc` took care of it automatically.
Here's a proposal for a more informative message. Note that the code is *not* enclosed in backticks. This allows users to select/copy/paste the lines from the error message directly in their consoles instead of typing them manually.
```shell
Error:
✖ `altdoc` needs `mkdocs` to be installed in a Python virtual environment. The best way to create the
required `.venv_altdoc` directory depends on your development environment. On a unix-like system, it usually
involves executing these commands from the root directory of your R package:
python -m venv .venv_altdoc
.venv_altdoc/bin/pip install …
```
> mkdocs: more informative virtual environment message

- NEWS.md
- R/altdoc_variables.R
- R/import_vignettes.R
- R/render_docs.R
- R/settings.R
- R/settings_quarto_website.R
- R/setup_github_actions.R
- inst/quarto_website/quarto_website.yml
- man-roxygen/altdoc_freeze.R
This PR enables the use of [`freeze`](https://quarto.org/docs/projects/code-execution.html#freeze) functionality for `_quarto` websites. To enable freezing results of a file, add the following yml either to `quarto_website.yml` to enable site-wide or to the frontmatter of individual `.qmd` files:
``` yml
execute:
freeze: auto
```
The rendering logic is changed just a bit to render directly into `docs/`. For packages using `altdoc`, after this change, you need to add `output-dir` to your `quarto_website.yml`:
``` yml
project:
type: website
output-dir: ../docs
```
Also fixed the annoying converting `: yes` to `: true`; there's a feature in `yaml` package
> Enable `freeze` functionality for `quarto_website`

- DESCRIPTION
- R/qmd2md.R
https://github.com/etiennebacher/altdoc/issues/270#issuecomment-2038185857
We already install `evaluate` anyway since it's one of the foundations of quarto/R Markdown:
``` r
pak::pkg_deps_explain("altdoc", "evaluate")
#> ℹ Loading metadata database✔ Loading metadata database ... done
#> altdoc -> quarto -> rmarkdown -> evaluate
#> altdoc -> quarto -> rmarkdown -> knitr -> evaluate
```
On a small test R package with 2 man pages, one of which has an error.
```r
> altdoc::render_docs(verbose = FALSE)
── Basic files ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔ README imported.
── Man pages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Found 2 man …
```
> Show error messages from quarto even if `verbose = FALSE`

- R/qmd2md.R
Trivial PR.
The recent addition of evaluate::evaluate() opened a new graphics device (window) every time we converted a file (sometimes hundreds of times for complex packages).
This is a one argument trivial change.
> evalutate::evaluate opens a new graphic device on every convert

- DESCRIPTION
- R/import_readme.R
- R/settings_quarto_website.R
- R/setup_docs.R
- inst/quarto_website/quarto_website.yml
- tests/testthat/test-setup_docs.R
Fix #292
I don't know if ideally we should render README.Rmd / qmd, but we should be able to fix the error for now anyway.
> fix: does not require README.qmd for Quarto website

- NEWS.md
- tests/testthat/helper.R
Useless PR just to trigger tests on main
> Fix test failure

- DESCRIPTION
- R/import_readme.R
- tests/testthat/test-render_docs.R
Depending on the type of README there were some errors when creating a quarto website
> Fix and tests for different types of README when `tool = "quarto_website"`
